version: "3.8"

services:
  mongodb:
    image: mongo:8.0.10
    container_name: todo-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-unver}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-12345}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    networks:
      - todo-app-network
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: todo-app-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: todo-app-mongodb
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT:-27017}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME:-unver}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:-12345}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-12345}
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    networks:
      - todo-app-network
    depends_on:
      - mongodb

  jenkins:
    image: jenkins/jenkins:2.516
    container_name: todo-app-jenkins
    ports:
      - "${JENKINS_UI_PORT:-8080}:8080"
      - "${JENKINS_PORT:-50000}:50000"
    networks:
      - todo-app-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb_data:
  jenkins_home:

networks:
  todo-app-network:
    name: todo-app-network
