version: "3.8"

services:
  mongodb:
    image: mongo:8.0.10
    container_name: todo-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-username}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: todo-app-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: todo-app-mongodb
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 12345
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongo_data:
