server:
  port: ${APP_PORT:3535}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:mongodb}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:user}
      password: ${MONGODB_PASSWORD:12345}
      authentication-database: admin

auth:
  enabled: true
