spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:username}
      password: ${MONGO_PASSWORD:password}
      authentication-database: admin
