spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:unver}
      password: ${MONGODB_PASSWORD:12345}
      authentication-database: admin

auth:
  enabled: false
